sudo: required
dist: trusty
language: node_js
node_js:
- node
cache: ccache
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libgcc-4.8-dev
    - libstdc++-4.8-dev
    - libobjc-4.8-dev
    - libjsoncpp0
    - libobjc-4.8-dev
    - libstdc++6
    - checkinstall
  sauce_connect:
    username:
      secure: awXNvlwMXZ0t419TKnB2Gfbg2CjU0fSmuCNq+rklGV3vQQPPweQjW7W4mdaMGr4UMzNlwlG+PKEabhwV/PmzZXhBfe1H9bJKO4TmsEONTO2i5WrYAHHXEpAwCpF3SUf1hecL0uS5dFel0mvJHrZwTdupLzFmEOLmt1N+b9z3DqfiP//Uc1aqnThsaflpz8MG4evVbUNPM/AiNlLTQTqZuIsmaoHGR7lqgwZSZWhB3x6ut5A7zEActWiFu4iSVdWA7l7pJInhvx8pEoL3vV2ZRIKLF0HexMk0Ykm+n5jO5BTpGm0GsxseBk6zK+AEeS4yAucj8DFr0QtiSgLaOwBwvrRMlF4ryzjzxmnC7x5wIpRSpyHP9XQQX+1q5LPAKNR/aYSjrWKJJhr00R7xQ2BQg7xMHYajcK4ILiX8kXXQZQ3aKXqDs6rpgUJqci2JMdfhziIlT1lnR7y5B3CLjWs70ZSvm+UP8cm/ZRfSrMm1NH2ENUnInRry938dIQq1lHgnk7JYjYuJy8VlG5tCmi2tac8LJCDd+/62Io2r5YTp5kc/+qMAuLonGit5mZYF4YaAJI1mWOjfAaIHyGnY+5O7t/mBJalngnE2q6QgcN6Dmdd7khO2AmNGCG44DpwTKSV69XyxbExrnSfmaibtYVmpfRt2XvDrF9fp2/FT239nUcw=
    access_key:
      secure: UiJJRJPRm5pH8quE2EvCooGkykll1MwadYMakTDPJIH3Ecn+fKOgntrovReJlwuH74Mi2sxS+7j8zrdOhd1fiOyY8zDgvAUEviWa2Q5UW82EdQ0ReVUtR6t63rSgFqhH20gsH1zPh96vIfmWRY52WACX3yBgmrMuZGjMStXzjXeBH2G5weWhYanbE6jRX/AWVuK25/etrzFWfXFYlXgZNptn9XBBsirxAv0QFjt0uBS4c3ANUd+MtKohlKdYdmUIPY/6uoWjZk3i7COmlWXKNsDsT+IuxTTx8DyMqUf1/9dn8/KobKBWlRWxM9Kzawn49ydJrkgSoAnYjTdUh5XCwq/sW/TWS7kWWZCBcJa9xL4M3e+6m2UDmgeX9jGZuD/OGE/5CSbL0Mv5YKGSY5Ek/rT+HCBGv/fXSXNLfSyX+KhS6/6ZchVj+KduEgTmKBuZ3x6N1pBfBT7HbgNBX3Opgxbs2iomXRcTDsrxEirLWrec5CsJ3pf/hhkBcjz1sBwze7ShYqbemEdNcVjtQtdhH+4Hm+JEuJILJoWajLMWTUL7tInokCc3F03w17bZIbafm+PjcUV30g+kE1F6axLt4GPBZVBBuuKOOyAWy1R47RCr4Teh5pLB+9byX5pXSZ0mUAirR2R5qwENh6cWmR2s/FU5QswGR0nGjX4Kohq84Lc=
  code_climate:
    repo_token:
      secure: i26rPVMhJbffCwkWfItH7fsmEK2bxjcxSj/+ktRK+RF7oaPJVzJzJHkEuJ7/WVz4tQJeul/+pSiInpyj6UkdOz1QMWHQ/liSIP3KlnUJ4JMqBn2jrFCgrVN3wPqwoa9zXuHsHoO/uLZzX2kqsPCwwypWLV95NgINUGUX6RLdnrxh+lrFmWsDwfmMeTfqobOXCSwCu1tX7MqHYHZhzakrunVGxlpiMUlHHPxb+4ap8cYv6JGWhxITQRJI/G/O1WprxgQu+j1xp6odXhZBkL0jeZHwOExj3YB56LTxDE3rZVhsMhMAawsHMJzr9CYNe5eR/zjlRD+uwS5649L0iFiHM0JpBK4igYi439zTqIfdQJlQnIxFUJ9yfOp41KbFF0tMGdpCDQc1brkxpuADQjrrFnlKnmXE13Y8iGnxKg0G1BxvyuviqmsHwVqVGosaoMbbEWy4X+sy7EGEf29PaDuPnoqCjZcZ/j3vVoyv8FJNTJfcwJAE68WT+tU5PZY4mBE3YIZqI/Zq39ndrLlooJ/8mF64119rpRVF6da4nXXgbo1nGn+S8Gv/+Tiu9XofrCQgsGTBhw5R1TpA6OCoNLVMYhVG6aW5Jyzxy/SoOVCfgxCfws94sNJi85R24RlnpY8Tki4D77JfRGmi0Fl1mWlEkTZ39ESsoCdSesnIuKSAJpA=
before_install:
- wget https://cmake.org/files/v3.7/cmake-3.7.2.tar.gz && tar -xf cmake-3.7.2.tar.gz
  && cd cmake-3.7.2 && ./configure && make -j2 && sudo checkinstall -y && cd ..
- wget http://famreiser.ch/llvm/llvm-5.0-303148-webassembly.tar.gz
- mkdir llvm && tar -xzf llvm-5.0-303148-webassembly.tar.gz -C llvm
- cd llvm && sudo dpkg -i clang-5.0_5.0~svn303148-1~exp1_amd64.deb libclang1-5.0_5.0~svn303148-1~exp1_amd64.deb
  libclang-5.0-dev_5.0~svn303148-1~exp1_amd64.deb libclang-common-5.0-dev_5.0~svn303148-1~exp1_amd64.deb
  libllvm5.0_5.0~svn303148-1~exp1_amd64.deb llvm-5.0_5.0~svn303148-1~exp1_amd64.deb
  llvm-5.0-runtime_5.0~svn303148-1~exp1_amd64.deb llvm-5.0-dev_5.0~svn303148-1~exp1_amd64.deb
  && cd ..
- sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-5.0 50
- sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang-5.0 50
- sudo update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-5.0 50
- sudo update-alternatives --install /usr/bin/llc llc /usr/bin/llc-5.0 50
- sudo update-alternatives --install /usr/bin/opt opt /usr/bin/opt-5.0 50
- sudo update-alternatives --install /usr/bin/llvm-nm llvm-nm /usr/bin/llvm-nm-5.0 50
- sudo update-alternatives --install /usr/bin/llvm-link llvm-link /usr/bin/llvm-link-5.0 50
- sudo update-alternatives --install /usr/bin/llvm-ar llvm-ar /usr/bin/llvm-ar-5.0 50
- sudo update-alternatives --install /usr/bin/llvm-as llvm-as /usr/bin/llvm-as-5.0 50
- export CC=clang-5.0
- export CXX=clang++-5.0

install:
- npm config set LLVM_CONFIG llvm-config-5.0
- npm install
- npm run bootstrap

after_success:
- npm run coverage

after_failure:
- cat npm-debug.log || true
- cat packages/compiler/npm-debug.log || true
- cat packages/runtime/npm-debug.log || true
- cat packages/benchmark/npm-debug.log || true
- cat lerna-debug.log || true
